### ISSUE TITLE
Unexpected behavior

### ISSUE THREAD

**Issue by ManiAm** [Bishalsarang/Recursion-Tree-Visualizer#25]
I have graphviz-5.0.1, python 3.10.6, windows 10.
Running the following code,

```
import os
os.environ["PATH"] += os.pathsep +  'C:/Program Files/Graphviz/bin/'

from visualiser.visualiser import Visualiser as vs

@vs(node_properties_kwargs={"shape":"record", "color":"#f57542", "style":"filled", "fillcolor":"grey"})
def fib(n):
    if n <= 1:
        return n
    return fib(n=n-1) + fib(n=n-2)

print(fib(n=3))
# Save recursion tree to a file
vs.make_animation("fibonacci.gif", delay=2)
```
produces an incorrect png/gif.

![fibonacci](https://user-images.githubusercontent.com/5473998/187024206-3f0cee30-82d7-4c9d-bc84-5b655627c6d1.png)

![fibonacci](https://user-images.githubusercontent.com/5473998/187024225-c08f985b-5768-4ff5-b414-5f81ab9ea50a.gif)

**Comment by Bishalsarang** [comment]
Seems like it is working for me. Can you try installing this version of [graphviz](https://www2.graphviz.org/Packages/stable/windows/10/msbuild/Release/Win32/) and see if that works

**Comment by ManiAm** [comment]
I found the root cause.
When I am running the script inside ipynb, then the script starts to misbehave.
Running the script directly seems to be ok.

**Comment by ManiAm** [comment]
inside ipynb, when I run two instances of the program one after the other, the results messed up together.

![2022-08-27_12-41-28](https://user-images.githubusercontent.com/5473998/187045660-e50f65a6-a4eb-4912-89e6-5a68cf2e08a3.png)

**Comment by ManiAm** [comment]
![fact](https://user-images.githubusercontent.com/5473998/187045677-ff1da570-39a3-4a29-b887-1c646bb9229b.png)

**Comment by Bishalsarang** [comment]
Thank you for the detailed steps for reproducing the issue. Will look into that.

**Comment by Bishalsarang** [comment]
The issue has been fixed and released in https://github.com/Bishalsarang/Recursion-Tree-Visualizer/releases/tag/v1.0.3

Install the latest version from pip and it should work fine.

**Comment by ManiAm** [comment]
thanks! it is working now.
