### ISSUE TITLE
[feature request] adding decorator to control graph properties

### ISSUE THREAD

**Issue by ManiAm** [Bishalsarang/Recursion-Tree-Visualizer#27]
similar to `node_properties_kwargs` that controls the node properties:

https://github.com/Bishalsarang/Recursion-Tree-Visualizer/blob/c9f794ec6b6b741246e8347ffd54efea06b1cb09/visualiser/visualiser.py#L26

it would be good to have `graph_properties_kwargs` that controls the graph properties.
For example, background color.
So that it is not hard-coded in the code:

https://github.com/Bishalsarang/Recursion-Tree-Visualizer/blob/c9f794ec6b6b741246e8347ffd54efea06b1cb09/visualiser/visualiser.py#L277

**Comment by Bishalsarang** [comment]
It would be great if you could open the PR for this feature. I think the change should be straightforward.
